version: 0.{build}
skip_tags: true
cache: C:\Users\appveyor\AppData\Local\NuGet\Cache
build_script:
- git submodule update --init --recursive
- powershell "& .\scripts\setup.ps1 -quiet"
- powershell "& .\scripts\replace-version.ps1"
- scripts\make.bat
- 7z a output-%APPVEYOR_BUILD_VERSION%-%APPVEYOR_REPO_COMMIT%.zip output/*
test: off
artifacts:
- path: output-*.zip
  name: garden-windows
deploy:
- provider: S3
  access_key_id: AKIAJ3M5ORCAISPRT22Q
  secret_access_key:
    secure: lMbaCusTBxZpIbSzoILyHMBkz+sVH7EwgAqI3sAVYAM92OcIzlzq1IzcB8MmnRvZ
  region: us-east-1
  bucket: garden-windows-release
  artifact: garden-windows
  set_public: true
  on:
    branch: master
clone_folder: c:\garden-windows-release
branches:
  only:
  - master
  - /appveyor/
